@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

class User {
    - idUser
    - name
    - pass
    - type
}

class Review {
    - idReview
    - status
    - text
    - rating
    - Date
}

class Vote {
    - idVote
    - vote
}

User "1" --- "*" Review:  has <
Review "1" --- "1" Vote: has >
User "1" --- "1" Vote: makes >


@enduml
