@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

class Product {
    - name
    - description
    - SKU
    - barCode
}

class Image {
    - idImage
    - SKU
    - path
}

Product "*" -right- "*" Image: has >

@enduml