@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Client" as client
participant "API" as api

activate client

client -> api: GET /moderator/reviews
api --> client: Return the list of all pending reviews




@enduml